sudo: false

language: go

go:
  - 1.12.x

env:
- GO111MODULE=on

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls

install:
  - make install

before_script:
  - make doc
  - if [[ `git status --porcelain` ]];
    then
      git diff;
      echo "'make doc' was not run before commiting";
      exit 1;
    fi
  - go test ./...

script:
  - if [[ $TRAVIS_TAG == v* && ! $TRAVIS_TAG =~ test ]];
    then
      curl -sL https://git.io/goreleaser | bash;
    fi

after_success:
  - make coveralls

notifications:
  email: false
